version: '3'
services:
  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
      - VITE_APPID=${VITE_APPID}
    env_file:
      - .env

  # Production service
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
      - VITE_APPID=${VITE_APPID}
    env_file:
      - .env
