# Step 1: Use the Node.js image for development
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy only the package.json and yarn.lock to install dependencies
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Command to run the development server
CMD ["yarn", "dev"]
