version: '3'
services:
  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173" # Port for Vite's dev server
    environment:
      - NODE_ENV=development

  # Production service
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" # Nginx will serve the production build on port 80
    environment:
      - NODE_ENV=production
